### PR TITLE
Special handling type definitions in `ScalaStructureBuilder`

### PR DESCRIPTION
**Pull request by mlangc**
This tweak fixes [#1002773](https://app.assembla.com/spaces/scala-ide/tickets/1002773-open-type-fails-for-type-aliases/details#). I'm not sure that I like it though, so your comments are highly welcome!

### CODE REVIEW

**Comment by mlangc** [comment]
Hmm, I can't reproduce this test failure locally... retest this please!

**Comment by sschaef** [comment]
retest this please

**Comment by sschaef** [comment]
I have never worked with this part of the codebase. If it works, it is fine by me.

**Comment by sschaef** [comment]
@mlangc What don't you like about this fix? maybe @wpopielarski wants to say something about it.

**Comment by mlangc** [comment]
@sschaef Since I don't have any experience with the related code and with JDT stuff in general, I thought that there might be a more elegant way to fix this bug than adding two nodes of different types for the same element.

**Comment by dragos** [comment]
LGTM, I think it's the minimal change that can support this use case.

**Comment by wpopielarski** [comment]
Well, I would need to look into it deeper. No experience in this area. @mlangc not sure maybe some test would be helpful? If you don't have time I try to figure out something

**Comment by wpopielarski** [comment]
generally area is interesting and I have a feeling that touches debugging model too (in phase when breakpoints are added)

**Comment by wpopielarski** [comment]
give me some day to look into it :)

**Comment by wpopielarski** [comment]
LGTM, @mlangc thanks for a hint how to fix "breakpoint not set" problem

**Pull request merged**
