### PR TITLE
Feature/outline backticks 1002590

### PR DESCRIPTION
**Pull request by andrey-ilinykh**
I fixed it by just looking into the source code.

### CODE REVIEW

**Comment by dragos** [comment]
Please add a `Fix #...` in the commit message. That automatically closes the ticket.

**Comment by dragos** [comment]
LGTM otherwise! Thanks!

**Comment by sschaef** [comment]
You have a merge error - the commits are doubled.

**Comment by dragos** [comment]
Closing this since we merged #1029

**Pull request closed without merging**
