### PR TITLE
Adds line delimiter depended on one found

### PR DESCRIPTION
**Pull request by wpopielarski**
in edited file

Depends on https://github.com/scala-ide/scala-refactoring/pull/188

### CODE REVIEW

**Comment by sschaef** [comment]
retest this please

**Comment by wpopielarski** [comment]
retest this please

**Comment by sschaef** [comment]
I don't know why it can't find the newest nightly for scala-refactoring. Maybe a cache problem for today. We can try again tomorrow

**Comment by wpopielarski** [comment]
no worries :) no hurry

2017-02-28 15:06 GMT+01:00 Simon Schäfer <notifications@github.com>:

**Comment by wpopielarski** [comment]
retest this please

**Comment by sschaef** [comment]
retest this please

**Comment by sschaef** [comment]
retest this please

**Comment by sschaef** [comment]
retest this please

**Comment by sschaef** [comment]
Finally, the tests passed. I will never understand how to teach maven to update snapshots. I killed the cache, that did it. 😟

**Pull request merged**
