### PR TITLE
Bug in step out functionality

### PR DESCRIPTION
**Pull request by wpopielarski**
scenario:
```
object Greeter {
  case object Greet
  case object GreetMe
  case object Unknown
  case object Done
}

class Greeter extends Actor {
  var toMe = 0
  var trigger: ActorRef = _
  var gritter = context.actorOf(Props[Gritter], "gritter")
  def receive = {
    case Greeter.GreetMe =>
      toMe = toMe + 1
      if (toMe < 5)
        self ! Greeter.GreetMe
      else {
        println("Hello World!")
        trigger ! Greeter.Done
      }
      gritter ! Greeter.GreetMe
    case Greeter.Greet =>
      trigger = sender()
      self ! Greeter.GreetMe
  }
}

class Gritter extends Actor {
  def receive = {
    case Greeter.Unknown =>
      println("misty misterious")
    case Greeter.GreetMe =>
      println("nice to see you")
  }
}

```
In case of many same messages there are lot of breakpoints on receive
which make a mess which gets stuck debugging process.

Fixed #1002541

### CODE REVIEW

**Comment by sschaef** [comment]
LGTM. @wpopielarski Would you please file a ticket for this thing and include the source snippet? After that you can mention the ticket in the commit as fixed.

**Comment by sschaef** [comment]
@wpopielarski I would like to merge this one. Can you please create a ticket and mark it in the commit message as fixed?

**Comment by wpopielarski** [comment]
ok,
sorry for late response, I had to give a lift my kids to school,
give me 15mins

2015-09-08 15:30 GMT+02:00 Simon Schäfer <notifications@github.com>:

**Comment by wpopielarski** [comment]
done (I hope)

**Comment by sschaef** [comment]
The commit message needs to mention the fix, not just the PR message.

**Comment by wpopielarski** [comment]
I though that there is a shortcut, now is done according to the state of art

**Comment by sschaef** [comment]
Now, everything is fine. LGTM

**Comment by wpopielarski** [comment]
thank

2015-09-09 11:55 GMT+02:00 Simon Schäfer <notifications@github.com>:

**Pull request merged**
