### PR TITLE
Adds some more data when remote debugging fails on connection to debu…

### PR DESCRIPTION
**Pull request by wpopielarski**
…gee machine

### CODE REVIEW

**Comment by wpopielarski** [comment]
retest this please

**Comment by wpopielarski** [comment]
retest this please

**Comment by sschaef** [comment]
The tests pass on my system but they always passed on my system. They failed on Scala Jenkins. The code looks LGTM therefore we can merge and then rerun on Scala Jenkins. Hopefully, it is fixed there too.

**Comment by wpopielarski** [comment]
I thought that they are failing on your local too. Actually I just tried to
build branch twice to see if anything went wrong, but unfortunately they
are green. Anyway I wonder if we can collect more data about failing
scenario. If so, we can decide what next after we see what's up.

2016-01-25 19:03 GMT+01:00 Simon Schäfer <notifications@github.com>:

**Comment by wpopielarski** [comment]
retest this please

**Comment by sschaef** [comment]
Unfortunately the test still fails on Scala Jenkins: https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-ide/2045/console

```
Tests in error: 
  terminateKillsRunningVM(org.scalaide.debug.internal.launching.RemoteConnectorTest): Unable to connect to the remote VM with args: port->44362hostname->localhosttimeout->20000
```

**Comment by wpopielarski** [comment]
good, looks that we need more data, what do you think just to add a check
if application is up?

2016-01-27 0:25 GMT+01:00 Simon Schäfer <notifications@github.com>:

**Pull request merged**
