### PR TITLE
Fixes problem with AssertionError thrown from scalap when potential b…

### PR DESCRIPTION
**Pull request by wpopielarski**
…ytecode has incorrect structure.

### CODE REVIEW

**Comment by Andrei-Pozolotin** [comment]
thank you

**Comment by lemillos** [comment]
Is this issue fixed? I am getting same problem.

**Comment by rkrzewski** [comment]
@lemillos Which Scala IDE version are you using? This fix was first included in 4.7.1-rc1.

**Comment by lemillos** [comment]
@rkrzewski according to eclipse "Eclipse Installation Details" view:

  JDT Weaving for Scala	4.7.1.v-2_12-201801021323-2dfe808	org.scala-ide.sdt.weaving.feature.feature.group	scala-ide.org
  Scala IDE for Eclipse	4.7.1.v-2_12-201801021323-2dfe808	org.scala-ide.sdt.feature.feature.group	scala-ide.org
    Scala 2.12.3	4.7.1.201801021322	org.scala-ide.scala212.feature.feature.group	scala-ide.org
    zinc 1.0.0	4.7.1.201801021322	org.scala-ide.zinc.feature.feature.group	scala-ide.org
  Scala Search	0.6.0.v-2_12-201801021356-5a19344	org.scala.tools.eclipse.search.feature.feature.group	org.scala.tools.eclipse
  Scala Worksheet	0.8.0.v-2_12-201801021348-8ec1baf	org.scalaide.worksheet.feature.feature.group	Scala IDE

eclipse_installations

**Comment by rkrzewski** [comment]
Looks like it's 4.7.1-rc3, so the fix in this PR is included.

**Comment by lemillos** [comment]
@rkrzewski so it should be fixed... but i am getting the same error message sometimes using the eclipse-IDE. I can not reproduce the error because it pops-up randomly (Maybe a Java Heap Space Error is the cause?)

**Comment by rkrzewski** [comment]
Unfortunately there is nobody left to fix it. Scala IDE is not actively maintained anymore. You can read about latest developments here https://gitter.im/scala-ide/scala-ide

**Comment by lemillos** [comment]
@rkrzewski Thank you so much! Appreciate

**Pull request merged**
