### PR TITLE
Prepare Scala IDE to run with scala 2.12.1

### PR DESCRIPTION
**Pull request by wpopielarski**

### CODE REVIEW

**Comment by wpopielarski** [comment]
retest this please

**Comment by sschaef** [comment]
https://jenkins.scala-ide.org:8496/jenkins/job/ghprb-scala-ide-multi-conf/eclipse_platform=eclipse-neon/733/

**Comment by wpopielarski** [comment]
retest this please

**Comment by sschaef** [comment]
retest this please

**Comment by sschaef** [comment]
A new run has been triggered now: https://jenkins.scala-ide.org:8496/jenkins/job/ghprb-scala-ide-multi-conf/eclipse_platform=eclipse-neon/737/

**Comment by sschaef** [comment]
retest this please

**Pull request merged**
