### PR TITLE
T1002180 remove old wizards

### PR DESCRIPTION
**Pull request by sschaef**
The 4.0 release is out and users have the time of an entire release to get familiar with the new wizard. Some bugs have been reported and already been fixed, therefore I'm for removing the old wizards finally.

### CODE REVIEW

**Comment by Kwestor** [comment]
What's up with a failing tests?

**Comment by sschaef** [comment]
What do you mean with failing tests?

**Comment by Kwestor** [comment]
This: failed test

**Comment by sschaef** [comment]
I thought this was because of a merge conflict but it is something else. A rebuild should work fine.

**Comment by Kwestor** [comment]
LGTM

**Comment by sschaef** [comment]
@dragos Do you want to review this before merging?

**Pull request merged**
