### PR TITLE
Flaky expression evaluator tests fix by blocking progress monitor for…

### PR DESCRIPTION
**Pull request by wpopielarski**
… creation and deletion of projects

### CODE REVIEW

**Comment by wpopielarski** [comment]
retest this please

**Comment by wpopielarski** [comment]
Retest this please

**Comment by wpopielarski** [comment]
retest this please

**Comment by wpopielarski** [comment]
retest this please

**Comment by wpopielarski** [comment]
retest this please

**Comment by wpopielarski** [comment]
retest this please

**Comment by wpopielarski** [comment]
retest this please

**Comment by sschaef** [comment]
retest this please

**Comment by sschaef** [comment]
The progress monitor was just for testing purposes and in the end the fix is the longer timeout?

**Comment by wpopielarski** [comment]
both are needed, progress monitor just holds test until workspace is
created and JDI timeout is to avoid Timeout exceptions.
Progress monitor solves error of type "thread expected to be SUSPENDED but
found TERMINATED"

2016-05-13 11:14 GMT+02:00 Simon Schäfer <notifications@github.com>:

**Comment by sschaef** [comment]
Ok, LGTM

**Pull request merged**
