### PR TITLE
Improve async debugger

### PR DESCRIPTION
**Pull request by sschaef**
- Re-enables the disabled "step to next message" feature
- Adds preference page to allow users to configure async program points
- Allow debugger commands to have key combinations (no default key combinations set, since it is difficult to find one that works on all systems)
- Move "step to next message" icon to async view toolbar

### CODE REVIEW

**Comment by dragos** [comment]
It seems both #994 and this PR added back "bang"... so which one is the right one? :)

**Comment by sschaef** [comment]
I'm going to merge the other PR first and then rebase this one on top of master. Then, the first commit should be gone.

**Comment by dragos** [comment]
Looks good, I like the new configuration dialog!

**Comment by sschaef** [comment]
Superseded by #997

**Pull request closed without merging**
