### PR TITLE
Update to Eclipse 4.7.0 (Oxygen)

### PR DESCRIPTION
**Pull request by rkrzewski**
Please note that Oxygen introduced binary incompatible changes. If this PR is merged as is to master, new versions of Scala IDE plugins will no longer work on Eclipse Neon and lower. Please let me know if this OK, or `platfom/oxygen` should stay as a separate branch for another Eclipse release cycle, or do we need a workaround for single sourcing the IDE for Neon and Oxygen.

### CODE REVIEW

**Comment by benmccann** [comment]
Thank you for this!

**Comment by godenji** [comment]
What's the status here? 

Scala 2.12.3 will soon be released, would be nice to get on the latest Scala and Eclipse releases -- that will give contributors a common base to work from moving forward. 

I've got a PR in the works that integrates latest Scalariform release into Eclipse Neon, but would prefer to adapt changes to scala-ide master branch *after* this PR gets merged in (hopefully soon).

**Comment by nilskp** [comment]
Can we get an ETA?

**Comment by rkrzewski** [comment]
According to what @wpopielarski said on [gitter](https://gitter.im/scala-ide/scala-ide) yesterday, next release for Neon can be expected before end of August and then for Oxygen mid-September.

If you are interested in doing some pre-relase testing, follow [Scala IDE on Eclipse Oxygen preview](https://groups.google.com/forum/?fromgroups#!topic/scala-ide-user/6L10KxVbZoQ) thread.

**Comment by sschaef** [comment]
@wpopielarski I tested this on the latest master and everything works fine. Are you ready to update to Eclipse Oxygen? I'm going to merge this then and remove support for Neon.

**Comment by wpopielarski** [comment]
I would merge zinc and your warnings fix change first and oxygen on it. just to be safe.

**Comment by wpopielarski** [comment]
exactly, Simon said that it is working ok, so I don't see the reason why
this guy needs to wait for separate release.

2017-08-28 11:28 GMT+02:00 Rafał Krzewski <notifications@github.com>:

**Comment by rkrzewski** [comment]
All right, I'll do that.
It is working fine: I've been using it for a few months and about 20 people downloaded my unofficial build in August alone. Never heard any complaints ;)

**Comment by rkrzewski** [comment]
FYI, I've run the build on [3495767](https://github.com/scala-ide/scala-ide/commit/3495767c4e6bfcda72473387a9cfdf985ec967d5) with #1178 and #1170 merged in, all tests are passing and IDE works fine on my projects (up-to-date binaries are at https://storage.googleapis.com/scalaide_4_6_oxygen/site/).
I think we are good to go :)

**Comment by wpopielarski** [comment]
cool!

2017-08-28 23:50 GMT+02:00 Rafał Krzewski <notifications@github.com>:

**Comment by nilskp** [comment]
:+1:

**Pull request merged**
