### PR TITLE
changed the create scala project description

### PR DESCRIPTION
**Pull request by lancewf**
Completed ticket 1002430. Had to add the description for the wizard. 

https://www.assembla.com/spaces/scala-ide/tickets/1002430#/activity/ticket:

### CODE REVIEW

**Comment by dragos** [comment]
add to whitelist

**Comment by sschaef** [comment]
The ticket commit message needs to include `Fix #1002430`

**Comment by lancewf** [comment]
I reverted the commit and did it with the correct message.

**Comment by sschaef** [comment]
No need to revert anything, you can rebase the commit with git. Also the commit message should not *only* include the `Fix #ticket` annotation but as an addition.

You can do the following on your branch:

```bash
git rebase -i 9ec8a42^
```
An editor opens with three lines (comment lines not included). Do the following:

1. Remove the line with the revert
2. change the third commit from 'edit' to 's'
3. close editor.

Another editor opens. Change the commit message here to something like:
```
Add description to "Create Scala Project" wizard

Fix #1002430
```
Close the editor once again and push the changes upstream.

**Comment by sschaef** [comment]
@lancewf Thanks for your work, however, the commit message still doesn't fit our guidelines. Now the first line is too long, it shouldn't exceed ~80 characters that form a single line in git. If you didn't find it already, here are our guidelines for commit messages: https://github.com/scala-ide/scala-ide/blob/master/CONTRIBUTING.md#creating-commits-and-writing-commit-messages

**Comment by sschaef** [comment]
Also, this PR should only include one commit, namely the one that fixes the bug. All the others should be removed.

**Comment by lancewf** [comment]
Thanks for the help @sschaef. I am going to try again from a fresh fork of the code. I am glad the code is only one line for this task.

**Comment by sschaef** [comment]
Superseded by #958

**Pull request closed without merging**
