### PR TITLE
Open declaration on function jumps to value

### PR DESCRIPTION
**Pull request by VlachJosef**
instead of to apply method. Fix for #1002087 from assembla.

Here is the link to [open ticket](https://scala-ide-portfolio.assembla.com/spaces/scala-ide/support/tickets/1002087).

Since I don't know how to run tests, I'm not sure if tests will run correctly after the changes I've made.

### CODE REVIEW

**Comment by sschaef** [comment]
ok to test

**Comment by sschaef** [comment]
retest this please

**Comment by sschaef** [comment]
The commit message needs to say `Fix #1002087` in a new line at the end.

**Comment by sschaef** [comment]
Beside from that LGTM

**Comment by VlachJosef** [comment]
I've added `Fix #1002087` at the end of the first line in my fork. Is that enough or should I edit header of this pull request instead?

**Comment by sschaef** [comment]
It is enough to change the commit message. But you need to put it to the end and not to the beginning. From this:
```
 Open declaration on function jumps to value (Fix #1002087)

instead of to apply method.
```
to this:
```
 Open declaration on function jumps to value

instead of to apply method.

Fix #1002087
```

**Comment by VlachJosef** [comment]
I see, commit message changed.

**Comment by sschaef** [comment]
Cool, thanks! A very nice fix!

**Pull request merged**
