### PR TITLE
Replaces AtomicReference

### PR DESCRIPTION
**Pull request by wpopielarski**
with oldfashioned synchronized because for threads contition spinning causes CPU overheating

fix #1002690

### CODE REVIEW

**Comment by sschaef** [comment]
retest this please

**Comment by sschaef** [comment]
The methods are synchronizes but wouldn't it be possible that multiple threads access different methods and therefore there could be a race condition when accessing `threads`?

**Comment by sschaef** [comment]
LGTM. The error is related to EE.

**Comment by wpopielarski** [comment]
Simon,

generally access to 'threads' should be atomic (so synchronious in this
time). AtomicReference was working pretty good. I think that main problem
was related to iulian's finding so :+ used instead of :: and permanent
recreation of 'prev :+ threadToAdd'. 'synchronized' just does it once but
blocks bigger range of code.
this is how I see it. I hope Iulian can correct me if I'm wrong.

2016-04-28 15:07 GMT+02:00 Simon Schäfer <notifications@github.com>:

**Pull request merged**
