### PR TITLE
Add Mars profile for building

### PR DESCRIPTION
**Pull request by dragos**
This makes the IDE compile under Eclipse 4.5 (Mars).

- added `eclipse-mars` profile in pom.xml, with proper dependency on the weaving.hook
- source changes for making it compile with Mars
- duplicated sources from `src-luna` to `src-mars` in the `sdt.core` and `sdt.aspects` projects

- [ ] check if we need to keep different source folders, or we can drop Luna altogether (maybe the build is binary compatible?)

### CODE REVIEW

**Comment by dragos** [comment]
I won't be able to work more on this, but this builds fine locally (and tests pass). I hope we can move our dev to Mars, since it's better than Luna, and that's what I'm using day to day.

**Comment by dragos** [comment]
retest this please

**Comment by dragos** [comment]
OK, the tests are failing now because of scalariform not being found as a P2 repository. @sschaef how is it supposed to work now? Via Maven snapshots? Then should we just remove the P2 repo from `pom.xml`?

**Comment by wpopielarski** [comment]
I'm not sure about that because I'm using luna by now, but Krzysztof alluded that mars uses same error icon for markers coming from compilation and presentation compiler. I need to verify it

**Comment by dragos** [comment]
I'm using Mars for a while now.. and I didn't notice anything.. These changes are only for being able to build the source code under Mars (the binary already runs under Mars). This is of benefit only for IDE developers, if they want to use the most recent Eclipse ;-)

**Comment by sschaef** [comment]
There are source incompatible changes between Luna and Mars. We can't just have one source folder, for both platforms.

**Comment by dragos** [comment]
Eclipse Mars passed! \o/

screen shot 2016-02-27 at 15 50 28

**Comment by dragos** [comment]
No, but maybe we don't have to. If the binaries run on Luna as well (to be checked, but in principle they should), we can just simplify the build and get rid of special source folders.

The good news is that the Maven build and tests pass, and the weaving hook version is the right one.

**Comment by sschaef** [comment]
Ok, in this case I also have to start to use Mars.

**Comment by dragos** [comment]
Closing this, please follow #1078

**Pull request closed without merging**
