### PR TITLE
Expression evaluator

### PR DESCRIPTION
**Pull request by sschaef**
Supersedes #874

See the previous PR for further information, this PR only handles the extraction of the expression evaluator from the main Scala IDE plugin to its own plugin with the name "org.scala-ide.sdt.debug.expression".

See the commit messages for more information and for challenges that had to be solved on the way.

TODO:

~~- [ ] 47 tests fail on Java8.~~

\cc @Kwestor, @pbatko, @pkukielka, @mpociecha, @romanowski, @rpokrywka

### CODE REVIEW

**Comment by Kwestor** [comment]
I'll look into those errors, maybe it's something I know.

**Comment by Kwestor** [comment]
Everything works for me. Do you run on Java 8 or 7? Because last time I checked some tests failed on 8.

**Comment by sschaef** [comment]
I run on Java 8. Everything fine then (or not).

**Comment by sschaef** [comment]
On Java 7, all tests pass on my system too. But I noticed that a lot of exceptions are shown in the log:
```
2015-03-09 15:09:58,301  INFO [main] - JdiExpressionEvaluator - Compiling:
short ^ double
2015-03-09 15:09:58,318  INFO [Java indexing] - ScalaSourceIndexer - Indexing document: /expr-eval-values/src/debug/package.scala
2015-03-09 15:09:58,321 ERROR [main] - JdiExpressionEvaluator - Applying phase: TypeCheck failed
Trees before current transformation:
------------ After phase 'Initial code': ------------

short.$up(double)

------------  After phase 'FailFast': ------------

short.$up(double)

------------  After phase 'SearchForUnboundVariables': ------------

short.$up(double)

------------  After phase 'MockAssignment': ------------

short.$up(double)

------------  After phase 'MockVariables': ------------

{
  val short: scala.Short = JdiContext.placeholder;
  val double: scala.Double = JdiContext.placeholder;
  val __this: debug.Values.type = JdiContext.placeholder;
  import __this._;
  ();
  short.$up(double)
}

------------  After phase 'AddImports': ------------

{
  import debug._;
  import org.scalaide.debug.internal.expression.context._;
  import org.scalaide.debug.internal.expression.proxies._;
  import org.scalaide.debug.internal.expression.proxies.primitives._;
  {
    val short: scala.Short = JdiContext.placeholder;
    val double: scala.Double = JdiContext.placeholder;
    val __this: debug.Values.type = JdiContext.placeholder;
    import __this._;
    ();
    short.$up(double)
  }
}

------------  After phase 'MockThis': ------------

{
  import debug._;
  import org.scalaide.debug.internal.expression.context._;
  import org.scalaide.debug.internal.expression.proxies._;
  import org.scalaide.debug.internal.expression.proxies.primitives._;
  {
    val short: scala.Short = JdiContext.placeholder;
    val double: scala.Double = JdiContext.placeholder;
    val __this: debug.Values.type = JdiContext.placeholder;
    import __this._;
    ();
    short.$up(double)
  }
}

------------  After phase 'MockTypedLambda': ------------

{
  import debug._;
  import org.scalaide.debug.internal.expression.context._;
  import org.scalaide.debug.internal.expression.proxies._;
  import org.scalaide.debug.internal.expression.proxies.primitives._;
  {
    val short: scala.Short = JdiContext.placeholder;
    val double: scala.Double = JdiContext.placeholder;
    val __this: debug.Values.type = JdiContext.placeholder;
    import __this._;
    ();
    short.$up(double)
  }
}
------------

scala.tools.reflect.ToolBoxError: reflective typecheck has failed: overloaded method value ^ with alternatives:
  (x: Long)Long <and>
  (x: Int)Int <and>
  (x: Char)Int <and>
  (x: Short)Int <and>
  (x: Byte)Int
 cannot be applied to (Double)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$typecheck$1.apply(ToolBoxFactory.scala:178)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$typecheck$1.apply(ToolBoxFactory.scala:170)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$transformDuringTyper$1$$anonfun$11.apply(ToolBoxFactory.scala:148)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$transformDuringTyper$1$$anonfun$11.apply(ToolBoxFactory.scala:148)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$transformDuringTyper$1$$anonfun$9.apply(ToolBoxFactory.scala:138)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$transformDuringTyper$1$$anonfun$9.apply(ToolBoxFactory.scala:138)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$transformDuringTyper$1$$anonfun$withContext$1$1.apply(ToolBoxFactory.scala:139)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$transformDuringTyper$1$$anonfun$withContext$1$1.apply(ToolBoxFactory.scala:139)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$transformDuringTyper$1$$anonfun$7.apply(ToolBoxFactory.scala:137)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$transformDuringTyper$1$$anonfun$7.apply(ToolBoxFactory.scala:137)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$transformDuringTyper$1.apply(ToolBoxFactory.scala:148)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$transformDuringTyper$1.apply(ToolBoxFactory.scala:121)
	at scala.reflect.internal.Trees$class.wrappingIntoTerm(Trees.scala:1716)
	at scala.reflect.internal.SymbolTable.wrappingIntoTerm(SymbolTable.scala:16)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.withWrapping$1(ToolBoxFactory.scala:120)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.transformDuringTyper(ToolBoxFactory.scala:121)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.typecheck(ToolBoxFactory.scala:169)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$$anonfun$typecheck$2.apply(ToolBoxFactory.scala:375)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$$anonfun$typecheck$2.apply(ToolBoxFactory.scala:367)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$withCompilerApi$.liftedTree2$1(ToolBoxFactory.scala:355)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$withCompilerApi$.apply(ToolBoxFactory.scala:355)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.typecheck(ToolBoxFactory.scala:367)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.typecheck(ToolBoxFactory.scala:27)
	at org.scalaide.debug.internal.expression.proxies.phases.TypeCheck.doTypeCheck$1(TypeCheck.scala:44)
	at org.scalaide.debug.internal.expression.proxies.phases.TypeCheck.transform(TypeCheck.scala:46)
	at org.scalaide.debug.internal.expression.ExpressionEvaluator$$anonfun$1.apply(ExpressionEvaluator.scala:150)
	at org.scalaide.debug.internal.expression.ExpressionEvaluator$$anonfun$1.apply(ExpressionEvaluator.scala:144)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at org.scalaide.debug.internal.expression.ExpressionEvaluator.org$scalaide$debug$internal$expression$ExpressionEvaluator$$transform(ExpressionEvaluator.scala:144)
	at org.scalaide.debug.internal.expression.ExpressionEvaluator$$anonfun$compileExpression$1.apply(ExpressionEvaluator.scala:78)
	at org.scalaide.debug.internal.expression.ExpressionEvaluator$$anonfun$compileExpression$1.apply(ExpressionEvaluator.scala:71)
	at scala.util.Try$.apply(Try.scala:191)
	at org.scalaide.debug.internal.expression.ExpressionEvaluator.compileExpression(ExpressionEvaluator.scala:71)
	at org.scalaide.debug.internal.expression.JdiExpressionEvaluator.apply(JdiExpressionEvaluator.scala:60)
	at org.scalaide.debug.internal.expression.BaseIntegrationTest.runInEclipse(BaseIntegrationTest.scala:56)
	at org.scalaide.debug.internal.expression.BaseIntegrationTest.evalWithToolboxError(BaseIntegrationTest.scala:48)
	at org.scalaide.debug.internal.expression.proxies.primitives.operations.bitwise.BitwiseXorTest.short$u0020$up$u0020sth(BitwiseXorTest.scala:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:123)
	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:87)
	at org.eclipse.tycho.surefire.osgibooter.HeadlessTestApplication.run(HeadlessTestApplication.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.equinox.internal.app.EclipseAppContainer.callMethodWithException(EclipseAppContainer.java:587)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:198)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
```

Is this expected?

**Comment by sschaef** [comment]
Also it seems to me that the tests are quite slow:
```
[INFO] org.scala-ide.sdt.build ............................ SUCCESS [  0.582 s]
[INFO] org.scala-ide.sdt.aspects .......................... SUCCESS [  4.473 s]
[INFO] org.scala-ide.sdt.core ............................. SUCCESS [ 37.131 s]
[INFO] org.scala-ide.sdt.core.tests ....................... SUCCESS [02:22 min]
[INFO] org.scala-ide.sdt.spy .............................. SUCCESS [  3.984 s]
[INFO] org.scala-ide.sdt.debug ............................ SUCCESS [ 11.547 s]
[INFO] org.scala-ide.sdt.debug.tests ...................... SUCCESS [01:07 min]
[INFO] org.scala-ide.sdt.debug.expression ................. SUCCESS [ 15.516 s]
[INFO] org.scala-ide.sdt.debug.expression.tests ........... SUCCESS [04:37 min]
[INFO] org.scala-ide.sdt.weaving.feature .................. SUCCESS [  0.084 s]
[INFO] org.scala-ide.sdt.feature .......................... SUCCESS [  0.099 s]
[INFO] org.scala-ide.sdt.dev.feature ...................... SUCCESS [  0.078 s]
[INFO] org.scala-ide.sdt.source.feature ................... SUCCESS [  0.042 s]
[INFO] org.scala-ide.sdt.update-site ...................... SUCCESS [  4.904 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10:05 min
[INFO] Finished at: 2015-03-09T15:10:45+01:00
[INFO] Final Memory: 156M/416M
[INFO] ------------------------------------------------------------------------
```
Maybe it is possible to share resources to speed them up?

**Comment by Kwestor** [comment]
About errors: this tests looks like that: `evalWithToolboxError("short ^ double")` and checks if compilation fails (it should, as this also fails in scalac).

About speed: right now every test suite runs debugger to certain breakpoint (defined by it's `BaseIntegrationTestCompanion`), then run's all tests and shuts down project. Do you have any ideas how to speed it up further?

**Comment by romanowski** [comment]
But we still missing breakpointHit(event.location, event.thread) call when condition return Success(true)

**Comment by sschaef** [comment]
Ok, I have to look into that again. Maybe it is best to register the default handling logic as another handler.

**Comment by sschaef** [comment]
The test suite is now completely hanging on my system (on Java7+8), not a single test can be started. Didn't this also happen on Jenkins some weeks earlier?

**Comment by Kwestor** [comment]
Yes, but only with `ConditionalBreakPointTest` (that's why those are commented out now).

I did not manage to reproduce it locally then.

**Comment by sschaef** [comment]
When I set a breakpoint in `BreakpointSupportActor` I get the following exception:
```
!ENTRY org.scala-ide.sdt.core 4 0 2015-03-18 14:43:52.722
!MESSAGE Shutting down org.scalaide.debug.internal.breakpoints.BreakpointSupportActor@75bbe6d7 because of
!STACK 1
org.eclipse.debug.core.DebugException: Breakpoint does not have an associated marker.
	at org.eclipse.debug.core.model.Breakpoint.ensureMarker(Breakpoint.java:290)
	at org.eclipse.jdt.internal.debug.core.breakpoints.JavaBreakpoint.getSuspendPolicy(JavaBreakpoint.java:989)
	at org.scalaide.debug.internal.breakpoints.BreakpointSupportActor$.org$scalaide$debug$internal$breakpoints$BreakpointSupportActor$$createBreakpointRequest(BreakpointSupport.scala:91)
	at org.scalaide.debug.internal.breakpoints.BreakpointSupportActor.classPrepared(BreakpointSupport.scala:204)
	at org.scalaide.debug.internal.breakpoints.BreakpointSupportActor.org$scalaide$debug$internal$breakpoints$BreakpointSupportActor$$applyDefaultHandling(BreakpointSupport.scala:147)
	at org.scalaide.debug.internal.breakpoints.BreakpointSupportActor$$anonfun$behavior$1.applyOrElse(BreakpointSupport.scala:166)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
	at scala.actors.ReactorTask.run(ReactorTask.scala:31)
	at scala.actors.Reactor$class.resumeReceiver(Reactor.scala:130)
	at org.scalaide.debug.internal.breakpoints.BreakpointSupportActor.scala$actors$InternalReplyReactor$$super$resumeReceiver(BreakpointSupport.scala:109)
	at scala.actors.InternalReplyReactor$class.resumeReceiver(InternalReplyReactor.scala:60)
	at org.scalaide.debug.internal.breakpoints.BreakpointSupportActor.resumeReceiver(BreakpointSupport.scala:109)
	at scala.actors.InternalActor$class.searchMailbox(InternalActor.scala:76)
	at org.scalaide.debug.internal.breakpoints.BreakpointSupportActor.searchMailbox(BreakpointSupport.scala:109)
	at scala.actors.Reactor$$anonfun$startSearch$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(Reactor.scala:118)
	at scala.actors.Reactor$$anonfun$startSearch$1$$anonfun$apply$mcV$sp$1.apply(Reactor.scala:115)
	at scala.actors.Reactor$$anonfun$startSearch$1$$anonfun$apply$mcV$sp$1.apply(Reactor.scala:115)
	at scala.actors.ReactorTask.run(ReactorTask.scala:33)
	at scala.actors.ReactorTask.compute(ReactorTask.scala:63)
	at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
which fails the test. Without a breakpoint no exception occurs and it seems that all running threads are in a waiting state - but I have no idea what they are waiting for.

**Comment by sschaef** [comment]
What should happen if a method definition is evaluated?
```
object CD extends App {
  def xs = List(1, 2, 3) map (_+"!")
  val x = 1 // breakpoint on this line
  println(x)
}
```
Evaluating `xs` (selecting the entire line) and sending it to EE works, but EE never answers.

**Comment by sschaef** [comment]
After the def is sent to EE, it consumes a lot of cpu power. The UI is also heavily unresponsive during that time. It can be seen when one tries to navigate through some menus or views.

**Comment by Kwestor** [comment]
We discovered last week evaluating single `val` or `def` makes `toolbox.compile` loops infinite somewhere. If you add something before or after (for example `2 + 2; val a = 1`) it works ok.

We don't know why this happens.

**Comment by sschaef** [comment]
Ok, did you report this as bug to the Scala team? Right now isn't the evaluation happening in its own process? I think we should go the hard route here and kill the process and respawn it if the user cancels the evaluation. Otherwise users are forced to restart Eclipse when the compiler goes crazy.

**Comment by sschaef** [comment]
I solved the hanging test suite thing. I introduced a bug in my latest commit, which was responsible for the hanging. I just wonder why it worked on Jenkins.

**Comment by Kwestor** [comment]
Not yet, I will investigate it tomorrow and create a work-around. Evaluation is run using some Eclipse-ish feature for running jobs, I don't remember which one was that.

btw - this message from Jenkins is really ugly...

**Comment by romanowski** [comment]
LGTM

**Comment by mpociecha** [comment]
I will review it properly later.

What about problems with JDK 8? I guess they should be fixed before we'll merge an evaluator. Does everything else in Scala IDE work with JDK 8?

**Comment by sschaef** [comment]
Scala IDE is ready for Java8 and I'm currently looking into getting EE working with Java8. Right now the remote VM somehow closes the connection, but I didn't yet find the reason why.

**Comment by mpociecha** [comment]
The current version seems to be okay.

**Comment by sschaef** [comment]
When I ask for the evaluation of an expression (here: https://github.com/sschaef/scala-ide/blob/01d476e5655825b4dc975f849dbc1e14c1e393fc/org.scala-ide.sdt.debug.expression/src/org/scalaide/debug/internal/expression/context/JdiMethodInvoker.scala#L309), where does the request arrive?

**Comment by Kwestor** [comment]
I'm not sure I follow, but `invokeMethod` is a JDI method implemented by Eclipse.

Btw - we are now developing some major changes and features for Expression Evaluator (on top of our old branch for now, see: https://github.com/Kwestor/scala-ide/compare/f22738f...84c6a76), and we should think about how to merge it here - now, or after this PR is merged?

**Comment by sschaef** [comment]
I already had a meeting with @romanowski about my last question where we cleared things up.

About your changes: I think beside from Java 8 support this PR is mostly finished and if further changes happen, they should be small. Therefore, I think it is best when you rebase your code now on top of this branch. That would decrease the risk of further merge errors.

**Comment by sschaef** [comment]
The last commit disables the failing test. I did not find out so far why the tests fail. There is now a ticket for the issue: https://www.assembla.com/spaces/scala-ide/tickets/1002428

If anyone has the time to look into this it would be nice if you could do it. Maybe you have some ideas where the problem could come from.

**Comment by Kwestor** [comment]
I just checked all tests on `jdk1.8.0_40` and it seems to work ok - both from IDE and from mvn.

It can be caused by some of changes we've made to EE that's not on this PR yet.

**Comment by Kwestor** [comment]
Yep, it's fixed "by accident" somewhere in our feature branch.

Which brings me to my next question: we have 40+ tasks done internally on EE ready to be ported on top of master and merged. Those have nice commit history with descriptions, feature branches etc.

@sschaef @dragos is it ok to create a single PR for those changes? Any further work after that new PR will be done on Github from the beginning, as we now have base code merged.

**Comment by sschaef** [comment]
Did you revert https://github.com/scala-ide/scala-ide/commit/92d61cdd80bd76780ba4342277dde54d9000bf9e in order to find out that the tests are really passing on Java8? If yes, that of course would be excellent.

I guess we can't review all of the code in every detail anyway, therefore I'm ok with opening only a single PR, but you should not kill the history as it was mostly done for this PR. Don't do fast forward merges either, they also kill information.

**Comment by mpociecha** [comment]
Our feature branch is not built on top of your branch which you've just merged. We simply don't have this commit.

**Comment by Kwestor** [comment]
Yes, it's based on the old version, before you extracted ee to separate project.

There are merge commits in this branch, I'm also strong advocate of keeping them as a source of useful metadata.

**Comment by Kwestor** [comment]
You can see it here: https://github.com/VirtusLab/scala-ide/commits/firefly-PR-02-23 (it's in private repo, but you should have access to it).

We have 3 more feature branches to review internally and merge there and then I'll rebase it to master and create a PR.

**Comment by sschaef** [comment]
Ok, you can then revert my last commit once you did all the merging.

@Kwestor No, I don't have access to this repo.

**Pull request merged**
