### PR TITLE
Adds 2.12 profile to tycho build.

### PR DESCRIPTION
**Pull request by wpopielarski**

### CODE REVIEW

**Comment by wpopielarski** [comment]
retest this please

**Comment by wpopielarski** [comment]
retest this please

**Comment by sschaef** [comment]
retest this please

**Comment by wpopielarski** [comment]
retest this please

**Comment by wpopielarski** [comment]
retest this please

**Comment by wpopielarski** [comment]
retest this please

**Comment by wpopielarski** [comment]
retest this please

**Comment by wpopielarski** [comment]
retest this please

**Comment by wpopielarski** [comment]
wrong way of problem solving

**Pull request closed without merging**
