### PR TITLE
Exposes configuration for new organize imports feature

### PR DESCRIPTION
**Pull request by wpopielarski**
Related to https://github.com/scala-ide/scala-refactoring/pull/155, will be built when  https://github.com/scala-ide/scala-refactoring/pull/155 merged

### CODE REVIEW

**Comment by sschaef** [comment]
retest this please

**Comment by sschaef** [comment]
retest this please

**Comment by sschaef** [comment]
There are compilation errors. Wieslaw, did you change the API or is this because the published artifacts are outdated (I republished them, therefore I don't think that is the case)?

**Comment by wpopielarski** [comment]
verifying...

**Comment by wpopielarski** [comment]
isn't a problem of scala-refactoring.jar version?

**Comment by wpopielarski** [comment]
not sure but looks like refactoring is taken from here: scala-ide/org.scala-ide.refactoring/org.scala-ide.refactoring.update-site/target/site
and inside /plugin is this guy:
org.scala-refactoring.library_0.11.0.2_11-201607110711-6636c10.jar

**Comment by wpopielarski** [comment]
should I update scala ide refactoring build?

**Comment by sschaef** [comment]
the build should consume the latest scala-refactoring nightly. If it doesn't do it anymore, then yes please update it.

**Comment by wpopielarski** [comment]
this is in target so it is taken from somewhere, trying to find from where

**Comment by wpopielarski** [comment]
S. 
this guy org.scala-refactoring.library_0.11.0.2_11-201607110711-6636c10.jar is taken from some p2 repo. I'm not sure but maybe it is related to 
```
<plugin>
<!--  create a better version number  -->
<groupId>org.eclipse.tycho</groupId>
<artifactId>tycho-packaging-plugin</artifactId>
<configuration>
<format>
'${version.tag}-${version.suffix}-'yyyyMMddHHmm'-${buildNumber}'
</format>
<archiveSite>true</archiveSite>
</configuration>
```

**Comment by wpopielarski** [comment]
@sschaef good man, just clean jenkins' local .m2 from old scala-refactoring

**Comment by sschaef** [comment]
retest this please

**Comment by sschaef** [comment]
retest this please

**Comment by sschaef** [comment]
Finally!

**Pull request merged**
