### PR TITLE
Fix for #1002486

### PR DESCRIPTION
**Pull request by wpopielarski**
Solves problem with not compiled java files when they depend on scala
files. Additionally there was a problem of disappearing error markers.

Fix #1002486

### CODE REVIEW

**Comment by sschaef** [comment]
This is how to use the fix ticket part of the commit message correctly:
```

How to update Assembla tickets from git commits

Use Closes assembla-4 or Closes #4 to close ticket 4. closed, close, fix, fixed, and fixes will also close a ticket.

Test assembla-4 or Test #4 will mark the ticket as "Ready to Test".

Re, references, refs and see will add a comment to the target ticket but leave it untouched.
```
Please update the last line of your commit messages accordingly. Otherwise, Assembla can not understand them.

**Comment by wpopielarski** [comment]
retest this please

**Comment by wpopielarski** [comment]
Simon,
now is ok?

**Comment by sschaef** [comment]
Looks great! :+1:

**Comment by sschaef** [comment]
LGTM

**Pull request merged**
