### PR TITLE
Throwing OCE if build was interrupted

### PR DESCRIPTION
**Pull request by sschaef**
Throwing OperationCancelledException when build was interrupted improve
responsiveness of build cancellation a lot in some cases.

Fixes #1002365

---
Only changes: 
- cleanup formatting in comments
- mention that ticket 1002365 is fixed

### CODE REVIEW

**Comment by sschaef** [comment]
Some private typesafe repo doesn't provide the necessary dependencies. Please provide them @dragos @skyluc

**Comment by Kwestor** [comment]
2.11.5 is out, and it's SNAPSHOTS were removed. It breaks Scala IDE build every time new Scala version is released.

**Comment by dragos** [comment]
I'll bump the Scala version in the pom file, but you'll need to rebase on master. I'll also need to publish Sbt artifacts for 2.11.6-SNAPSHOT

**Comment by dragos** [comment]
retest this please

**Comment by dragos** [comment]
In fact, 2.11.5-SNAPSHOTS are still there, and being published [on sonatype](https://oss.sonatype.org/content/repositories/snapshots/org/scala-lang/scala-compiler/2.11.5-SNAPSHOT/). Might be a transient failure.

**Comment by dragos** [comment]
LGTM

**Pull request merged**
